#!/usr/sbin/nft -f
# originally based on example at /usr/share/doc/nftables/examples/workstation.nft

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0;
        iif lo accept
        ct state established,related accept

        # allow SSH from everywhere
        tcp dport 22 ct state new accept

        # allow ping from everywhere
        iif wg-server icmp type echo-request accept
        iif wg-server icmpv6 type echo-request accept

        # ICMPv6 packets which must not be dropped, see https://tools.ietf.org/html/rfc4890#section-4.4.1
        meta nfproto ipv6 icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, echo-reply, echo-request, nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert, 148, 149 } accept
        ip6 saddr fe80::/10 icmpv6 type { 130, 131, 132, 143, 151, 152, 153 } accept

        {% if 'wireguard_server' in pillar -%}
        # allow the wireguard server ingress port
        udp dport {{ pillar["wireguard_server"]["port"] }} accept

        # grant access to salt
        iif wg-server tcp dport { 4505, 4506 } ct state new accept
        {%- endif %}

        {% if 'nftables' in pillar %}
        # additional content via pillar data for {{ grains["id"] }}
        {{ pillar["nftables"].get("content", {}).get("filter", {}).get("input", "# -") }}
        {%- endif %}

        # count and block any other traffic
        counter reject
    }
}
