mine_interval: 5 # minutes
mine_functions:
  mine_wireguard_pub:
    - mine_function: cmd.run
    - "cat /etc/wireguard/key.secret | wg pubkey"
    - python_shell: True
  mine_wireguard_psk:
    - mine_function: cmd.run
    - "cat /etc/wireguard/psk.secret"
    - python_shell: True
{% if grains["id"] == "knox.chaostreff-osnabrueck.de" %}
  mine_wireguard_hosts:
    - mine_function: cmd.run
    - "cat /etc/wireguard/wg-salt-hosts.txt"
{% endif %}
