reactor:
    #- 'salt/key': # teacting to a new key did not work, as the minion is not yet started / connected and hence the state.apply gets lost...
    #    - salt://salt/reactor/new.sls # this path is also somehow not working, although it should...
    - 'salt/minion/*/start':
        - /srv/salt/reactor/start.sls
