# salt-minion sometimes has a very bad time connecting to the master, so let's make sure it comes up (at some point) and doesn't just give up after a few tries
[Service]
Restart=always
RestartSec=10s
RestartSteps=4
RestartMaxDelaySec=160s
