# salt-minion sometimes has a very bad time connecting to the master, so let's make sure it comes up (at some point) and doesn't just give up after a few tries
[Service]
Restart=always
RestartSec=10s

# Prevent the service from entering the failed state due to too many restarts
StartLimitBurst=0
StartLimitIntervalSec=0
