[Interface]
Address = 10.13.37.1/32
PrivateKey = INJECT_PRIVATE_KEY_HERE
ListenPort = 12753

{% for _, hosts in salt['mine.get'](grains['id'], 'mine_wireguard_hosts') | dictsort() %}
{% for server in hosts.split('\n') %}{% if server in salt['mine.get'](server, 'mine_wireguard_pub') %}
# {{ server }}
[Peer]
PublicKey = {{ salt['mine.get'](server, 'mine_wireguard_pub').get(server) }}
{% if server in salt['mine.get'](server, 'mine_wireguard_psk') -%}
PresharedKey = {{ salt['mine.get'](server, 'mine_wireguard_psk')[server] }}
{%- endif %}
AllowedIPs = 10.13.37.{{ loop.index + 1 }}/32
PersistentKeepalive = 60
{% endif %}{% endfor %}{% endfor %}
