[Interface]
Address = {{ address }}/32
PrivateKey = INJECT_PRIVATE_KEY_HERE

[Peer]
PublicKey = {{ peer_key }}
Endpoint = {{ peer_endpoint }}
{% if peer_psk %}PresharedKey = {{ peer_psk }}{% endif %}
AllowedIPs = {{ peer_ip }}/32
PersistentKeepalive = 30
