[Interface]
Address = {{ pillar["wireguard_server"]["subnet"].format(1) }}/32
PrivateKey = INJECT_PRIVATE_KEY_HERE
ListenPort = {{ pillar["wireguard_server"]["port"] }}

{% set instance_hosts = salt['mine.get'](grains["id"], 'wireguard_vpn_server:hosts').get(grains["id"]) %} # TODO this should be read diretly from file
{% for peer_id, peer_public_key in salt['mine.get']('*', "wireguard_vpn_server:" + pillar["wireguard_server"]["id"] + ":client") | dictsort() %}
{% set peer_psk = salt['mine.get'](peer_id, "wireguard_vpn_server:" + pillar["wireguard_server"]["id"] + ":psk").get(peer_id) -%}

{% set peer_address_ns = namespace(found=None) -%}      
{% for line in instance_hosts.split('\n') %}{% if line.strip() == peer_id -%}
{% set peer_address_ns.found = pillar["wireguard_server"]["subnet"].format(loop.index + 1) -%}
{% endif %}{% endfor -%}

# {{ peer_id }}
{% if peer_address_ns.found -%}
[Peer]
PublicKey = {{ peer_public_key }}
{% if peer_psk %}PresharedKey = {{ peer_psk }}{% endif %}
AllowedIPs = {{ peer_address_ns.found }}/32
PersistentKeepalive = 60
{% else -%}
# The peer has not gotten an address assigned yet...
{% endif %}
{% endfor %}
